### PR TITLE
test for staging sprint 6.19_2

### PR DESCRIPTION
**Pull request by sysctstage**
Tracked-On: OAM-68413
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: ResetGerritApprovals Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/650

**Review by shenya1x — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE: ResetGerritApprovals Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/652

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-staging/builders/opensource-preintegration/builds/509

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
cactus finished building and testing your changes 

It was requested for merge by ctstage@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-staging/builders/opensource-mergerequest/builds/361

**Pull request merged**
