### PR TITLE
add branch2 file for dev

### PR DESCRIPTION
**Pull request by shenya1x**
Tracked-On: OAM-66902
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by sysctstage — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: Trigger Builds Triggered: build-cel - r1 (gordon_peak) - extra, build-cel - r1 (gordon_peak_acrn)

For more information, see: /absp-staging/builders/opensource-autobuild/builds/314

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE: Trigger Builds Triggered: build-cel - r1 (gordon_peak) - extra, build-cel - r1 (gordon_peak_acrn)

For more information, see: /absp-staging/builders/opensource-autobuild/builds/315

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/18

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/13

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
cactus finished building and testing your changes 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/opensource-mergerequest/builds/78

**Pull request merged**
