### PR TITLE
test for staging sprint 6.18

### PR DESCRIPTION
**Pull request by sysctstage**
Tracked-On: OAM-68236
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/646

**Review by shenya1x — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-staging/builders/opensource-preintegration/builds/502

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE: ResetGerritApprovals Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/647

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cel - r1 (aosp_x86), build-cel - r2 (gordon_peak), build-cel - r2 (gordon_peak_acrn) - extra

More details, logs, and binaries: /absp-staging/builders/opensource-preintegration/builds/503

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cel - r1 (aosp_x86), build-cel - r2 (gordon_peak), build-cel - r2 (gordon_peak_acrn) - extra

More details, logs, and binaries: /absp-staging/builders/opensource-preintegration/builds/504

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-staging/builders/opensource-preintegration/builds/505

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-staging/builders/opensource-premerge/builds/134

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
cactus finished building and testing your changes 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-staging/builders/opensource-mergerequest/builds/348

**Pull request merged**
