### PR TITLE
test for staging sprint 6.19_hotfix_3

### PR DESCRIPTION
**Pull request by shenya1x**

### CODE REVIEW

**Review by sysctstage — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/502

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/503

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/504

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/505

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/185

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: Create pub Artifactory Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/736

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: Create pub Artifactory Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/736

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/1

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/0

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/3

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/1

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/4

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/5

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Create pub Artifactory

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/6

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/7

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/8

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/10

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/11

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/2

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/12

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/13

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/14

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/15

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/16

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/69

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/70

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/71

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/75

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/4

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
cactus finished building and testing your changes 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/opensource-mergerequest/builds/14

**Pull request merged**
