### PR TITLE
test for staging sprint 6.18

### PR DESCRIPTION
**Pull request by sysctstage**
Tracked-On: OAM-68411
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: ResetGerritApprovals Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/648

**Review by shenya1x — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/662

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cel - r1 (aosp_x86), build-cel - r2 (gordon_peak), build-cel - r2 (gordon_peak_acrn) - extra

More details, logs, and binaries: /absp-staging/builders/opensource-preintegration/builds/513

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-staging/builders/opensource-preintegration/builds/514

Done by "Shen, YangX" <yangx.shen@intel.com>

**Pull request closed without merging**
