### PR TITLE
add mixin-fake-output for test

### PR DESCRIPTION
**Pull request by sysctstage**
add mixin-fake-output for test

Tracked-On: OAM-67726
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by shenya1x — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/317

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/571

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/572

**Review by sysctstage — COMMENTED** [review]
cactus finished building and testing your changes 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/opensource-mergerequest/builds/463

**Pull request merged**
