### PR TITLE
test for staging sprint 6.18

### PR DESCRIPTION
**Pull request by sysctstage**
Tracked-On: OAM-68193
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by shenya1x — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/641

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/640

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/426

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/427

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn) - extra

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/430

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/431

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/134

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/433

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/136

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/435

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/138

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-staging/builders/opensource-preintegration/builds/500

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-staging/builders/opensource-premerge/builds/132

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn) - extra

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/439

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/440

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/441

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/142

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn)

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/442

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn)

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/443

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/444

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/143

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/445

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/144

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn)

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/446

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn)

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/447

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn)

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/448

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:no target_products to build Generate multi manifest original json

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/449

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn)

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/450

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn)

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/451

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn)

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/452

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/453

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Generate multi manifest original json

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/454

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/455

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Generate multi manifest original json

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/456

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Generate multi manifest original json

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/457

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Generate multi manifest original json

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/458

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/459

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/460

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/148

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/149

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/466

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/157

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/468

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/159

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/469

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/161

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/472

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/163

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/474

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/165

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/476

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/166

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (aosp_x86), build-for_integration_tests - r2 (gordon_peak), build-for_integration_tests - r2 (gordon_peak_acrn) - extra

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/478

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/480

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/168

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/483

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/171

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/484

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/172

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/487

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/488

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/491

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
cactus finished building and testing your changes 

It was requested for merge by yangx.shen@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/opensource-mergerequest/builds/882

**Pull request merged**
