### PR TITLE
Branch5ff

### PR DESCRIPTION
**Pull request by sysctstage**

### CODE REVIEW

**Review by shenya1x — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/560

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/273

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/561

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/64

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/279

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/70

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/281

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/283

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/288

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/74

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/289

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/295

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/300

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (gordon_peak) - extra

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/301

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/302

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/82

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Compute Dependencies The change (u'a/hardware/intel/PRIVATE/platform_test', 3909) (a/hardware/intel/PRIVATE/platform_test,platform/android/for_integration_tests) was not come from the cactus branch opensource

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/312

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/313

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Compute Dependencies Cannot find on which Cactus branch the git project 'a/bsp/device/intel/cherrytrail', on git branch 'android/opensource', is configured as 'mergeable' (ie, not readonly).
For information, this project, on the same git branch, does NOT even appear as 'readonly' in any of the configured manifests.
Please check with Monitoring and Control to configure this project.
 The change (u'a/bsp/device/intel/cherrytrail', 3901) (a/bsp/device/intel/cherrytrail,android/opensource) can not find cactus branch in manifest server

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/314

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/316

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/321

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/323

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/324

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/325

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/326

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/327

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r2 (gordon_peak)

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/335

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/336

Done by "Shen, YangX" <yangx.shen@intel.com>

**Pull request merged**
