### PR TITLE
test for staging sprint 6.19_hotfix_4

### PR DESCRIPTION
**Pull request by shenya1x**

### CODE REVIEW

**Review by sysctstage — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/510

**Review by sysctstage — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/511

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/512

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/189

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/190

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/0

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: Create pub Artifactory Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/736

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: Create pub Artifactory Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/736

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Compute Dependencies The change (u'sysctstage/bootable-live-installer', 68) is in MERGED status, and MERGED patches are forbidden.

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/2

**Pull request merged**
